# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - astra_right_arm_controller
    - astra_right_hand_controller

  astra_right_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_r1
      - joint_r2
      - joint_r3
      - joint_r4
      - joint_r5
      - joint_r6
    action_ns: follow_joint_trajectory
    default: true
  astra_right_hand_controller:
    type: GripperCommand
    joints:
      - joint_r7l
      - joint_r7r
    action_ns: gripper_cmd
    default: true